version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript-package/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "America/New_York"
    reviewers:
      - "bgrnwd"
      - "tyler-richardett"
      - "doug-wade"
