name: ✨ Feature Request
description: Submit a feature request
title: "[Feature Request]: <title>"
labels: ["feature-request"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What feature would you like to see?
      placeholder: Tell us what you want.
    validations:
      required: true
