name: CRAN publish
on:
  release:
    types: [created]

jobs:
  cran-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v1
      # TODO publish to CRAN
