# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: JavaScript tests

on:
  workflow_dispatch:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "javascript-package/**"
      - ".github/workflows/javascript-tests.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: |
          cd javascript-package
          npm ci
          npm run build --if-present
          npm test
