# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: R-CMD-check
on:
  push:
    paths:
      - "R-package/**"
      - ".github/workflows/R-CMD-check.yml"

jobs:
  R-CMD-check:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(pkgdir = "./R-package", dependencies = TRUE)
        shell: Rscript {0}

      - name: R CMD check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(path = "./R-package", args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(path = "./R-package", token = "${{ secrets.CODECOV_TOKEN }}")
        shell: Rscript {0}
