# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: R-CMD-check
on:
  workflow_dispatch:
    branches: [main]
  push:
    paths:
      - "R-package/**"
      - ".github/workflows/R-CMD-check.yml"

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: R-package

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install OS-level dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev
        shell: bash

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: R CMD check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = "--no-manual",
            error_on = "warning",
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
