# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: R-CMD-check
on:
  workflow_dispatch:
    branches: [main]
  push:
    paths:
      - "R-package/**"
      - ".github/workflows/R-CMD-check.yml"

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: R-package

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v1

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
